# These are supported funding model platforms.
# Uncomment and fill in to enable the "Sponsor" button on this repository.

# github: [yniantongtian-oss]
# patreon: # replace with your Patreon username
# open_collective: # replace with your Open Collective slug
# ko_fi: # replace with your Ko-fi username
# tidelift: # replace with your Tidelift platform/package
# community_bridge: # replace with your Community Bridge project name
# liberapay: # replace with your Liberapay username
# issuehunt: # replace with your IssueHunt username
# lfx_crowdfunding: # replace with your LFX Crowdfunding project slug
# polar: # replace with your Polar username
# buy_me_a_coffee: # replace with your Buy Me a Coffee username
# thanks_dev: # replace with your thanks.dev username
# custom: # ['https://example.com/donate']
