name: uncloud
description: >-
  Uncloud — a local-first photo & file manager that syncs between phone and PC
  over LAN. No cloud. No account. No server.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
